name: be-harvester CI
on:
  push:
    branches:         
    - master   
jobs:
  build-and-push:
    name: Build and push image to AWS ECR
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAUQT3O5EFEXWSNZWB
        aws-secret-access-key: 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
        aws-region: us-east-1
    # see: https://github.com/aws-actions/amazon-ecr-login
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 310570313994.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: nodejs
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 310570313994.dkr.ecr.us-east-1.amazonaws.com/nodejs:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: 'trivy-results.sarif'



#aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 310570313994.dkr.ecr.us-east-1.amazonaws.com
