name: be-harvester CI
on:
  push:
    branches:         
    - master   
jobs:
  build-and-push:
    name: Build and push image to AWS ECR
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIASW2LZCVTK2ZKSQJX
        aws-secret-access-key: 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
        aws-region: us-east-2
    # see: https://github.com/aws-actions/amazon-ecr-login
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 186453136742.dkr.ecr.us-east-2.amazonaws.com
        ECR_REPOSITORY: nodejs
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


#aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 310570313994.dkr.ecr.us-east-1.amazonaws.com
